# launcher name & url
# Psina fork: имя НЕ содержит "ZalithLauncher"/"ZL" (GPLv3 §7)
launcher_name=PsinaEngine
launcher_app_name=Psina Engine
launcher_short_name=PE
url_home=https://github.com/pyBIrtat/PsinaEngine

# your OAuth client id
#oauth_client_id=xxx

# your CurseForge API key
#curseforge_api_key=xxx

# default key, please add it yourself.
default_store_password=vh#nn%N(#eNjwfA78-77s6&f-cdd(@-7eana-e%!nhj%))!@c
default_key_password=sfv72ghSSNQaadf99-Q69!2

# Psina fork: version обязан отличаться от апстрима (GPLv3 §7)
launcher_version_code=200107
launcher_version_name=2.6.1-psina.8